import tkinter as tk
from tkinter import ttk, messagebox
import os

class BeautifulApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Advanced Python Studio")
        self.root.geometry("600x450")
        self.root.configure(bg="#1e1e2e")  # Dark theme background

        # Configure Styles
        self.style = ttk.Style()
        self.style.theme_use("clam")
        self.style.configure("TButton", font=("Helvetica", 11), padding=10, background="#89b4fa", foreground="#11111b")
        self.style.map("TButton", background=[("active", "#b4befe")])

        # Header Title
        self.title_label = tk.Label(
            root, text="✨ Python Executable Dashboard ✨", 
            font=("Helvetica", 18, "bold"), fg="#cdd6f4", bg="#1e1e2e"
        )
        self.title_label.pack(pady=20)

        # Decorative Frame simulating an image/display area
        self.display_frame = tk.Frame(root, bg="#313244", highlightbackground="#585b70", highlightthickness=2)
        self.display_frame.pack(pady=10, padx=40, fill="both", expand=True)

        self.status_label = tk.Label(
            self.display_frame, text="System Ready. Click below to initialize safe file operations.", 
            font=("Helvetica", 11, "italic"), fg="#a6adc8", bg="#313244", wraplength=450
        )
        self.status_label.pack(expand=True, pady=20)

        # Interactive Button
        self.action_btn = ttk.Button(root, text="Execute Safe Read/Write Test", command=self.run_test)
        self.action_btn.pack(pady=30)

        # Footer
        self.footer = tk.Label(root, text="Compiled via PyInstaller • Safe Environment", font=("Helvetica", 9), fg="#585b70", bg="#1e1e2e")
        self.footer.pack(side="bottom", pady=10)

    def run_test(self):
        filename = "demo_output.txt"
        try:
            # Safe Write Operation
            with open(filename, "w", encoding="utf-8") as f:
                f.write("This file was safely generated by your custom Python executable!\n")
                f.write(f"Execution path: {os.path.abspath(filename)}")

            # Safe Read Operation
            with open(filename, "r", encoding="utf-8") as f:
                content = f.read()

            # Update the UI with results
            self.status_label.config(
                text=f"✅ Success!\n\nCreated and verified file structure.\n\n[File Contents]:\n{content}",
                fg="#a6e3a1", font=("Helvetica", 11, "normal")
            )
            messagebox.showinfo("Operation Complete", f"File safely generated at:\n{os.path.abspath(filename)}")

        except Exception as e:
            messagebox.showerror("Error", f"Failed to execute file operations: {str(e)}")

if __name__ == "__main__":
    root = tk.Tk()
    app = BeautifulApp(root)
    root.mainloop()
